---
  .travis.yml:
    hc_secure: "TwRhMSxwNCGMJ60itd5MxfFY0OKm1JJM8atk3x/A6+WFVY8odbV+/n0+VN0x\nDoKRvy8K44KO9mTRfrJP9Rep7MzGYiftq/fU/ZtWLNxHre3Gud5QmsZ6PmQz\njh+KzKlCM50kWX/mMOvmfI/qYx2cw0v9hddS6/jb0w+SkzmUVWo="

