---
  .travis.yml:
    hc_secure: "SmCxYy9T9DBZf09TNTUfCjaeAPJrYe2hsUlPajdWWIjlTUtE2yZESiIa3YGxw8qTjebafbH3BZc5Yu2zckHbFj94YbCa1xVRFt4mgT5W9/y9mZqz4VqyzFvQDYYohe/fDW6n+0ftu/3FIhBlU7yop8IeOdmmTTYe+s1NQcblNa0="

